export const ERR_CONNECTION_REFUSED = 'ERR_CONNECTION_REFUSED';

export const posts = {
	GET_ALL_POSTS: 'GET_ALL_POSTS',
	ADD_POST: 'ADD_POST',
	DELETE_POST: 'DELETE_POST',
	FIND_POST_BY_NAME: 'FIND_POST_BY_NAME',
};
